# Dependabot configuration for Synap
# See https://docs.github.com/en/code-security/dependabot

version: 2
updates:
  # Rust dependencies
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    reviewers:
      - "synap-maintainers"
    labels:
      - "dependencies"
      - "rust"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    ignore:
      # Ignore patch updates for stable dependencies
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    reviewers:
      - "synap-maintainers"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore(ci)"
      include: "scope"

  # TypeScript SDK dependencies
  - package-ecosystem: "npm"
    directory: "/sdks/typescript"
    schedule:
      interval: "weekly"
      day: "tuesday"
    open-pull-requests-limit: 10
    reviewers:
      - "synap-maintainers"
    labels:
      - "dependencies"
      - "typescript"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    versioning-strategy: increase

