name: Rust Linting

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  rustfmt:
    name: Format Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install Rust nightly
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt

      - name: Check code formatting
        run: cargo +nightly fmt --all -- --check

  clippy:
    name: Clippy Lints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install Rust nightly
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          key: clippy

      - name: Run Clippy (workspace)
        run: cargo clippy --workspace -- -D warnings

      - name: Run Clippy (all targets)
        run: cargo clippy --workspace --all-targets -- -D warnings

      - name: Run Clippy (all features)
        run: cargo clippy --workspace --all-targets --all-features -- -D warnings

  cargo-deny:
    name: Security & License Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install cargo-deny
        uses: taiki-e/install-action@cargo-deny

      - name: Check security advisories
        run: cargo deny check advisories

      - name: Check licenses
        run: cargo deny check licenses
        continue-on-error: true

      - name: Check bans
        run: cargo deny check bans
        continue-on-error: true

  cargo-audit:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install cargo-audit
        uses: taiki-e/install-action@cargo-audit

      - name: Run security audit
        run: cargo audit
        continue-on-error: true

